filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
build:
    environment:
        php:
            version: 7.4
    dependencies:
        before:
            # When updating the phpunit version make sure to also update it in the github workflow
            - composer require phpunit/phpunit:^9.5 --dev --ignore-platform-reqs
    tests:
        override:
            -
                command: bin/phpunit --coverage-clover=clover.xml
                coverage:
                    file: clover.xml
                    format: php-clover
